import assert from 'node:assert/strict';
import {dispatch,classifyReceipt} from '../tools/beeper-sender.mjs';
const row={id:'request',source_chat_id:'local-id',account_id:'account',text:'Exact <text>\n  with spaces '};
let posts=[],finishes=[];
const deps={getChat:async()=>({id:'canonical-chat',accountID:'account'}),send:async(...args)=>{posts.push(args);return {pendingMessageID:'pending'};},finish:async(...args)=>{finishes.push(args);}};
await dispatch(row,deps);
assert.deepEqual(posts,[['canonical-chat',row.text]]);assert.equal(finishes[0][1],'submitted');
posts=[];finishes=[];
await dispatch(row,{...deps,getChat:async()=>({id:'wrong',accountID:'different'})});
assert.equal(posts.length,0);assert.equal(finishes[0][1],'failed');
finishes=[];let attempts=0;
await dispatch(row,{...deps,send:async()=>{attempts++;throw Error('timeout');}});
assert.equal(attempts,1);assert.equal(finishes[0][1],'uncertain');
finishes=[];
await dispatch(row,{...deps,send:async()=>{throw Object.assign(Error('rejected'),{beforeSend:true});}});
assert.equal(finishes[0][1],'failed');
attempts=0;
await assert.rejects(dispatch(row,{...deps,send:async()=>{attempts++;return {pendingMessageID:'pending'};},finish:async()=>{throw Error('database offline');}}));
assert.equal(attempts,1);
assert.equal(classifyReceipt({sendStatus:{status:'SUCCESS'}}),'sent');
for(const status of ['FAIL_PERMANENT','FAIL_RETRIABLE'])assert.equal(classifyReceipt({sendStatus:{status}}),'failed');
for(const status of ['PENDING',undefined])assert.equal(classifyReceipt({sendStatus:{status}}),'submitted');
console.log('PASS: exact recipient/account/text, pending vs sent, no resend after ambiguous timeout or database failure. No live messages sent.');
