import assert from 'node:assert/strict';
import {dispatch,classifyReceipt,resolveReceipt} from '../tools/beeper-sender.mjs';
const row={id:'request',source_chat_id:'local-id',account_id:'account',text:'Exact <text>\n  with spaces '};
let posts=[],finishes=[];
const deps={getChat:async()=>({id:'canonical-chat',accountID:'account'}),send:async(...args)=>{posts.push(args);return {pendingMessageID:'pending'};},finish:async(...args)=>{finishes.push(args);}};
await dispatch(row,deps);
assert.deepEqual(posts,[['canonical-chat',row.text]]);assert.equal(finishes[0][1],'submitted');
posts=[];finishes=[];
await dispatch(row,{...deps,getChat:async()=>({id:'wrong',accountID:'different'})});
assert.equal(posts.length,0);assert.equal(finishes[0][1],'failed');
finishes=[];let attempts=0;
await dispatch(row,{...deps,send:async()=>{attempts++;throw Error('timeout');}});
assert.equal(attempts,1);assert.equal(finishes[0][1],'uncertain');
finishes=[];
await dispatch(row,{...deps,send:async()=>{throw Object.assign(Error('rejected'),{beforeSend:true});}});
assert.equal(finishes[0][1],'failed');
attempts=0;
await assert.rejects(dispatch(row,{...deps,send:async()=>{attempts++;return {pendingMessageID:'pending'};},finish:async()=>{throw Error('database offline');}}));
assert.equal(attempts,1);
assert.equal(classifyReceipt({sendStatus:{status:'SUCCESS'}}),'sent');
for(const status of ['FAIL_PERMANENT','FAIL_RETRIABLE'])assert.equal(classifyReceipt({sendStatus:{status}}),'failed');
for(const status of ['PENDING',undefined])assert.equal(classifyReceipt({sendStatus:{status}}),'submitted');
console.log('PASS: exact recipient/account/text, pending vs sent, no resend after ambiguous timeout or database failure. No live messages sent.');
const receiptRow={...row,message_id:'~pending',requested_at:'2026-09-08T16:00:00Z'};
const observed={id:'final',chatID:'canonical-chat',accountID:row.account_id,isSender:true,text:row.text,timestamp:'2026-09-08T16:00:02Z'};
assert.equal(classifyReceipt(observed,'~pending'),'recorded');
assert.equal(classifyReceipt({...observed,sendStatus:{status:'PENDING'}},'~pending'),'submitted');
assert.equal(classifyReceipt({...observed,sendStatus:{status:'FAIL_PERMANENT'}},'~pending'),'failed');
const receiptDeps={getChat:deps.getChat,getMessage:async()=>observed,listMessages:async()=>{throw Error('Unexpected fallback');}};
assert.deepEqual(await resolveReceipt(receiptRow,receiptDeps),observed);
assert.deepEqual(await resolveReceipt({...receiptRow,text:'  '+row.text+'\n'},receiptDeps),observed);
const fallback={...receiptDeps,getMessage:async()=>{throw Error('404 retired ID');},listMessages:async()=>({items:[observed],hasMore:false})};
assert.deepEqual(await resolveReceipt(receiptRow,fallback),observed);
assert.equal(await resolveReceipt(receiptRow,{...fallback,listMessages:async()=>({items:[observed,{...observed,id:'second'}],hasMore:false})}),null);
for(const patch of [{accountID:'wrong'},{chatID:'wrong'},{text:'different'},{isSender:false},{timestamp:'2026-09-08T15:00:00Z'}])assert.equal(await resolveReceipt(receiptRow,{...fallback,listMessages:async()=>({items:[{...observed,...patch}],hasMore:false})}),null);
let pages=0;
assert.deepEqual(await resolveReceipt(receiptRow,{...fallback,listMessages:async()=>++pages===1?{items:[{...observed,text:'newer',timestamp:'2026-09-08T16:00:20Z'}],hasMore:true,oldestCursor:'next'}:{items:[observed],hasMore:false}}),observed);
console.log('PASS: missing optional receipt, retired pending ID, bounded paginated fallback, ambiguous duplicates and wrong recipient rejection.');
